chapter-five/sharing-content/bookmarks/images/urls.py
from django.urls import path
from . import views

app_name = 'images'

urlpatterns = [
    path('create/', views.image_create, name='create'),
    path('detail/<int:id>/<slug:slug>/',views.image_detail, name='detail'),
    path('like/', views.image_like, name='like'),
]

chapter-five/sharing-content/bookmarks/images/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse

class Image( models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,related_name='images_created',on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, blank=True)
    url = models.URLField()
    image = models.ImageField(upload_to='images/%Y/%m/%d/')
    description = models.TextField(blank=True)
    created = models.DateField(auto_now_add = True, db_index=True)
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL,related_name='images_liked',blank=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('images:detail', args=[self.id, self.slug])

    

chapter-five/sharing-content/bookmarks/images/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import ImageCreateForm
from .models import Image
from django.http import JsonResponse
from django.views.decorators.http import require_POST

@login_required
def image_create(request):
    if request.method == 'POST':
        #form is sent
        form = ImageCreateForm(data=request.POST)
        if form.is_valid():
            #form data is valid
            cd = form.cleaned_data
            new_item = form.save(commit=False)

            #assign current user to the item
            new_item.user = request.user

            new_item.save()
            messages.success(request, 'Image added successfully')

            #redirect to new created item detail view
            return redirect(new_item.get_absolute_url())

    else:
        #build form with data provided by the bookmarklet via GET
        form = ImageCreateForm(data=request.GET)

    return render(request, 'images/image/create.html',{'section': 'images', 'form': form})


def image_detail(request, id, slug):
    image = get_object_or_404(Image, id=id, slug=slug)
    return render(request,'images/image/detail.html', {'section': 'images', 'image': image})

@login_required
@require_POST
def image_like(request):
    image_id = request.POST.get('id')
    action = request.POST.get('action')
    if image_id and action:
        try:
            image = Image.objects.get(id=image_id)
            if action == 'like':
                image.users_like.add(request.user)

            else:
                image.users_like.remove(request.user)
            return JsonResponse({'status':'ok'})

        except:
            pass

        return JsonResponse({'status': 'error'})

chapter-five/sharing-content/bookmarks/images/templates/images/image/detail.html
{% extends "base.html" %}

{% block title %}{{ image.title }} {% endblock %}

{% block content %}

    <h1>{{ image.title }}</h1>
    <!-- <img src="{{ image.image.url }}" class="image-detail"> -->

    {% load thumbnail %}
        <a href="{{ image.image.url }}">
            <img src="{% thumbnail image.image 300*0 %}" class="image-detail">
        </a>
    <!-- {% with total_likes = image.users_like.count %} -->
        {% with total_likes = image.users_like.count users_like = image.users_
            like.all %}
        <div class="image-info">
            <div>
                <span class="count">
                    <span class="total">{{ total_likes }}</span>
                    {{ total_likes }} likes{{ total_likes|pluralize }}
                </span>
                <a href="#" data-id="{{ image.id }}" data-action="{% if 
                    request.user in users_like %}un{% endif %}like"
                    class="like button">
                    {% if request.user not in users_like %}
                        Like
                    {% else %}
                        Unlike
                    {% endif %}
                </a>
            </div>
            {{ image.description|linebreaks }}
        </div>
        <div class="image-likes">
            <!-- {% for user in image.users_like.all %} -->
                {% for user in users_like %}
                <div>
                    <img src="{{ user.profile.photo.url }}">
                    <p>{{ user.first_name }}</p>
                </div>
            {% empty %}
                Nobody likes this image yet.
            {% endfor %}
        </div>
    {% endwith %}
    
{% endblock %}

{% block domready %}

    $('a.like').click(function(e){
        e.preventDefault();
        $.post('{% url "images:like" %}',
        {
            id: $(this).data('id'),
            action: $(this).data('action')
        },
        function(data){
            if (data['status'] == 'ok')
            {
                var previous_action = $('a.like').data('action');

                //toggle data-action
                $('a.like').data('action',previous_action == 'like' ?
                'Unlike' : 'like');

                //toggle link text
                $('a.like').text(previous_action == 'like' ? 'Unlike' : 'Like');

                //update total likes
                var previous_likes = parseInt($('span.count .total').text());

                $('span.count .total').text(previous_action == 'like' ?
                previous_likes + 1 : previous_likes - 1);
            }
        }
        );
    });       

{% endblock %}

chapter-five/sharing-content/bookmarks/images/templates/images/image/list.html
{% extends "base.html" %}

{% block title %}Images bookmarked{% endblock %}

{% block content %}

    <h1>Images bookmarked</h1>
    <div id="image-list">
        {% include "images/image/list_ajax.html" %}
    </div>
{% endblock %}

{% block domready %}

    var page = 1;
    var empty_page = false;
    var block_request = false;

    $(window).scroll(function(){
        var margin = $(document).height() - $(window).height() - 200;
        if ($(window).scrollTop() > margin && empty_page == false &&
        block_request == false) {
            block_request = true;
            page += 1;
            $.get('?page=' + page, function(data){
                if(data == ''){
                    empty_page = true;
                }
                else {
                    block_request = false;
                    $('#image-list').append(data)
                }
            });

        }
    });

{% endblock %}

chapter-five/sharing-content/bookmarks/images/templates/images/image/list_ajax.html
{% load thumbnail %}

{% for image in images %}

    <div class="image">
        <a href="{{ image.get_absolute_url }}">
            
            {% thumbnail image.image 300x300 crop="smart" as im %}

            <a href="{{ image.get_absolute_url }}">
                <img src="{{ im.url }}" alt="">
            </a>
            
        </a>

        <div class="info">
            <a href="{{ image.get_absolute_url }}" class="title" >
                {{ image.title }}
            </a>
        </div>

    </div>

{% endfor %}